# Generated by Django 5.1.3 on 2024-11-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_discount_percent'),
        ('general', '0004_paymentmethod'),
        ('orders', '0003_remove_order_coupon_code_remove_order_coupon_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.paymentmethod'),
        ),
    ]
