# Generated by Django 5.1.3 on 2024-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_general_shipping_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
